name: safclassifier
description: Flutter Application to handle SAF associates classification

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.1
  equatable: ^1.0.0
  dio: ^3.0.10
  flutter_bloc: ^4.0.0
  cupertino_icons: ^1.0.0
  shared_preferences: ^0.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.2.0
  build_runner: ^1.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: GothamRounded
      fonts:
        - asset: assets/fonts/gotham-bold.otf
        - asset: assets/fonts/gotham-book.otf
        - asset: assets/fonts/gotham-light.otf
        - asset: assets/fonts/gotham-medium.otf
